name: foxwren tests
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: sudo apt-get update
      - run: sudo apt-get install libx11-dev libxcb1-dev libx11-xcb-dev libegl-dev libgles-dev libsystemd-dev libudev-dev libinput-dev libdrm-dev libgbm-dev libxkbcommon-dev
      - run: zig build
      # - run: zig build -fstage1 (stage 1 doesn't support packed struct(u32))
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: zig fmt --check src/*.zig
